---
# builds, pushes
name: S3 Binary Workflow
on: [push]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: go build -o built .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Push to S3
        run: aws s3 cp built s3://ops.us-east-1.embedfi/protogen/linux-amd64/$(basename $GITHUB_REPOSITORY)


